---
# sssd_client_for_openldap/tasks/configure_sssd.yml

- name: "Create {{ path_to_sssd_conf }}"
  ansible.builtin.template:
    src: 'etc_sssd_sssd.conf.j2'
    dest: "{{ path_to_sssd_conf }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    'Restart SSSD service'
