---
# sssd_client_for_openldap/tasks/disable_nscd_caching.yml

- name: 'Check if the nscd.conf is existing'
  stat:
    path: "{{ path_to_nscd_conf }}"
  register: check_for_nscd_conf

- name: 'Disable host and group caching in nscd.conf, if it exists'
  lineinfile:
    path: "{{ path_to_nscd_conf }}"
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
    backrefs: 'yes'
  loop:
    - regex: '^(\s*enable-cache\s*passwd\s*)'
      line: '\1no'
    - regex: '^(\s*enable-cache\s*group\s*)'
      line: '\1no'
  when: 'check_for_nscd_conf.stat.exists | bool'
  notify:
    'Restart SSSD service'

- name: 'Populate service facts'
  service_facts:
  check_mode: 'false'

- name: 'Disable the nscd service completely'
  service:
    name: "{{ nscd_service_name }}"
    state: 'stopped'
    enabled: 'false'
    masked: 'true'
  when:
    - 'ansible_facts.services[nscd_service_name] is defined'
  notify:
    'Restart SSSD service'
