---
# sssd_client_for_openldap/tasks/enable_sssd_on_SUSE_openSUSE.yml

- name: 'Add sss in /etc/nsswitch.conf'
  ansible.builtin.lineinfile:
    path: '/etc/nsswitch.conf'
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - regex: '^passwd:\scompat'
      line: 'passwd: compat sss'
    - regex: '^group:\s.*'
      line: 'group:  compat sss'
  notify:
    - 'Restart SSSD service'

- name: 'Check if sss is enabled in the /etc/pam.d/common* files'
  ansible.builtin.command:
    cmd: "grep sss /etc/pam.d/common-account-pc /etc/pam.d/common-auth-pc /etc/pam.d/common-password-pc /etc/pam.d/common-session-pc"
  register: grep_for_sss_in_pam_files
  changed_when: 'false'
  failed_when: 'false'
  check_mode: 'false'

- name: 'Run pam-config if sss is not yet in the configuration files'
  ansible.builtin.command:
    cmd: 'pam-config -a --sss'
  when:
    - 'grep_for_sss_in_pam_files.stdout == ""'
  notify:
    - 'Restart SSSD service'
