---
# sssd_client_for_openldap/tasks/enable_sssd_via_authconfig

- name: 'Check if USESSSD is already enabled in /etc/sysconfig/authconfig'
  command:
    cmd: 'grep USESSSD=yes /etc/sysconfig/authconfig'
  register: usesssd_in_sysconfig_authconfig
  check_mode: 'false'
  changed_when: 'false'
  failed_when: 'usesssd_in_sysconfig_authconfig.rc != 0 and usesssd_in_sysconfig_authconfig.stdout != ""'

- name: 'Run authconfig --enablesssd --update'
  command:
    cmd: 'authconfig --enablesssd --update'
  when: 'usesssd_in_sysconfig_authconfig.stdout == ""'

- name: 'Check if USESSSDAUTH is already enabled in /etc/sysconfig/authconfig'
  command:
    cmd: 'grep USESSSDAUTH=yes /etc/sysconfig/authconfig'
  register: usesssdauth_in_sysconfig_authconfig
  check_mode: 'false'
  changed_when: 'false'
  failed_when: 'usesssdauth_in_sysconfig_authconfig.rc != 0 and usesssdauth_in_sysconfig_authconfig.stdout != ""'

- name: 'Check if sss is already in configuration files'
  shell:
    cmd: 'grep sss /etc/pam.d/*'
  register: sss_in_pam_configuration
  check_mode: 'false'
  changed_when: 'false'
  failed_when: 'sss_in_pam_configuration.rc != 0 and sss_in_pam_configuration.stdout != ""'

- name: 'Run authconfig --enablesssdauth --update'
  command:
    cmd: 'authconfig --enablesssdauth --update'
  when: 'sss_in_pam_configuration.stdout == "" or usesssdauth_in_sysconfig_authconfig == ""'
